### ISSUE TITLE
Spec version in the ED?

### ISSUE THREAD

**Issue by LJWatson** [w3c/pointerlock#17]
The link to the ED in the [Pointer Lock 2 FPWD](https://www.w3.org/TR/2016/WD-pointerlock-2-20161122/) seems to point to Pointer Lock 1?

**Comment by scheib** [comment]
I'm sorry, I don't understand yet.

The ED version is published as
https://w3c.github.io/pointerlock/
from the source file
https://github.com/w3c/pointerlock/blob/gh-pages/index.html

It currently has the "Latest editor's draft" set to the ED link I list
above.

I'm not aware of a "Pointer Lock 2 FPWD" being published formally beyond
the ED version.

**Comment by LJWatson** [comment]
I put the wrong link into my original comment (corrected now). The [FPWD](https://www.w3.org/TR/2016/WD-pointerlock-2-20161122/) was published on 22 November 2016, based on the [CFC](https://github.com/w3c/pointerlock/issues/12).

**Comment by scheib** [comment]
Thanks for clarifying. I did not prepare the v2 FPWD, and don't see the work done in https://github.com/w3c/pointerlock/tree/gh-pages/publish

@siusin, you helped in the past with publication, did you do the work for the FPWD?

I think these would be good steps to take:

1. Identify who published the FPWD to https://www.w3.org/TR/2016/WD-pointerlock-2-20161122/
1. Find the document source that was used
1. Compare against the ED https://github.com/w3c/pointerlock/blob/gh-pages/index.html
1. Merge all changes possible to the ED draft, including name change
1. Fork the ED from /index.html to /publish/index-2016-11-22-v2-FPWD.thml
1. Merge all remaining changes from the published FPWD to that file in github

I'm happy to perform steps 3 onward.

**Comment by siusin** [comment]
@scheib I'd like to propose a new step, to use our auto-publication system to sync the ED in GitHub and the WD under w3.org/TR;

If you agree with the idea, I'll enable this repo in the system, after that, any change in the [ED](https://w3c.github.io/pointerlock/) will trigger a new publication of the WD. Does it make sense to you?

**Comment by siusin** [comment]
Btw, ReSpec complained about the legacy ref to MDN-SetCapture. I've submitted a [PR ](https://github.com/tobie/specref/pull/353)to fix this.

**Comment by scheib** [comment]
Regarding syncing github -> w3.org/TR: It's probably better to have a single ED published location, and if it is being edited on github then one location already exists. So, I'd prefer we don't have an ED version anywhere but the single github location. However, I'll go with whatever the working group is doing broadly - consistency is good!

I still need help with #2 from my [last comment](https://github.com/w3c/pointerlock/issues/17#issuecomment-293979170); can I get the source that was used to publish https://www.w3.org/TR/2016/WD-pointerlock-2-20161122/

**Comment by siusin** [comment]
It's really up to the editors, if you prefer to keep the ED separated from the WD, then let's hold the plan to auto-publication.

I submitted a [pull request](https://github.com/w3c/pointerlock/pull/18) to add the snapshot of FPWD :) Please let us know if there's anything we can do to help.

**Comment by scheib** [comment]
Thanks, as I mention on the [pull request](https://github.com/w3c/pointerlock/pull/18) my intent is to capture the spec source used to produce the FPWD, any chance you still have that?

**Comment by siusin** [comment]
I'm afraid not... it was reset when I updated the repo last time. The way I generated the FPWD should be: 1) do a `git pull` to fetch the latest documents in the repo; 2) change the "`specStatus`" in the respecConfig to "FPWD"; 3) save a snapshot from ReSpec document and put it under /TR (we are still using CVS).

How about we publish a new WD using the current ED? Will it help?

**Comment by scheib** [comment]
I've updated ED source to be pointerlock-2 with https://github.com/w3c/pointerlock/commit/5caaf81899b5e6157dee4e7f63b4870d6a37b552

**Comment by siusin** [comment]
Thanks @scheib ! Please let us know when you think it's the right to publish a new WD :)

**Comment by scheib** [comment]
Ok. There hasn't been a meaningful change since FPWD yet, so.. no update
yet.
