### ISSUE TITLE
Time at TPAC?

### ISSUE THREAD

**Issue by LJWatson** [w3c/pointerlock#22]
Would you like time at [TPAC](https://www.w3.org/2017/11/TPAC/) to update the WG on progress and/or bring issues up for discussion?

Please let me know by Friday 16th June. If yes, please also let me know how much time you think you'll need.

**Comment by scheib** [comment]
If not too late, I'd work in a call for implementation interest in "Pointer Clip" https://github.com/w3c/pointerlock/issues/27

**Comment by LJWatson** [comment]
No problem. Can you give me an estimate of how long you'd like? Blocks of 30 minutes are useful measures.

**Comment by scheib** [comment]
Thanks. I think 30 minutes is more than enough. I think it would progress
faster than that -- we really just need to find out if implementation teams
are interested, so I think 15 minutes would be plenty.

Our Input Team lead will be at TPAC, but not Friday. Is there any
visibility for what days these types of topics will happen? If possible,
would prefer it earlier than Friday.

Thanks.

**Comment by LJWatson** [comment]
It's likely to be Thursday. We're just putting the draft schedule together at the moment and hope to post it later today/early next week.

**Comment by scheib** [comment]
Scheduled https://github.com/w3c/WebPlatformWG/issues/94
