### ISSUE TITLE
movementX/Y to be double instead of long

### ISSUE THREAD

**Issue by NavidZ** [w3c/pointerlock#24]
Following [the extension](https://drafts.csswg.org/cssom-view/#extensions-to-the-mouseevent-interface) that changes screenX/Y type to double I'd suggest we also change the type of movementX/Y to double. @scheib do you imagine any scenario that this might break stuff for any developers?

**Comment by scheib** [comment]
I think movementX should be modified the same as screenX. I do not think this will break any existing use. I've opened https://github.com/w3c/csswg-drafts/issues/1634 to help determine where to make this spec change.

**Comment by NavidZ** [comment]
@smaug---- I was looking at these properties and screenX/Y for pointerevents and mouseevents on FF. It seems that even screenX/Y is long for pointerevents. Do you think it is possible to change FF to expose double coordinates for pointerevents and also move the movementX/Y to double accordingly?

**Comment by smaug----** [comment]
should be doable. If nothing else, it is just a webidl change.

**Comment by NavidZ** [comment]
Maybe the type is correct by there might be some sort of rounding/flooring happen for that. For example in Chrome we do that for MouseEvents for compat reasons. So even though the type is double the numbers that are exposes are long. But we thought since pointerevents are new we just expose the double version of the number.

**Comment by mustaqahmed** [comment]
As @smaug---- mentioned above, changing the webidl types to fractional is the first step anyway, and then we can do [what we did before](https://github.com/w3c/pointerevents/issues/107#issuecomment-232939986):
- PointerEvent's movement coordinates will be fractional, and
- MouseEvent's movement coordinates will be rounded to integers, and we drop the rounding here later on if the compat risk is low.

@EiraGe has agreed to look into this.
