### ISSUE TITLE
Add pointerlock to the permissions enum

### ISSUE THREAD

**Issue by scheib** [w3c/pointerlock#5]
As described in https://github.com/w3c/permissions/issues/67, Pointer Lock should add a definition and then request Permissions spec to incorporate the enum.

**Comment by annevk** [comment]
Should it? It is only gesture gated…

**Comment by scheib** [comment]
I still need to read the permissions spec in detail. 

However, requestPointerLock permits a user agent to gate the feature behind a permission request. Chrome, Firefox, and Edge initially implemented with these prompts. Chrome changed to permit Pointer Lock without explicit permission prompt in early 2016. Today Firefox and Edge still prompt for permission.

**Comment by annevk** [comment]
Firefox is changing that. Might have already landed in Nightly.

**Comment by scheib** [comment]
Note that Firefox nightly today still uses a permission. firefox-52.0a1.en-US.linux-x86_64.tar.bz2

However, I agree that browsers are likely to trend towards not having a permission prompt here. The pointer lock specification allows that, but I don't currently see a need to add this detail to the permissions specification.
