### ISSUE TITLE
No matching definition found for `triggered by user activation`

### ISSUE THREAD

**Issue by janiceshiu** [w3c/pointerlock#53]
On the [latest editor's draft](https://w3c.github.io/pointerlock/), there is 1 respec error. 

`Couldn't match "triggered by user activation" to anything in the document or in any other document cited in this specification: dom, fetch, html, infra, url, webidl. See how to cite to resolve the error at: 1.`

I could not find this term in [respec xref](https://respec.org/xref/). 

This is the line that triggers the error.
https://github.com/w3c/pointerlock/blob/1ce79b70a0a9a3f89720dd5af7b22ba1a5a84440/index.html#L165

**Comment by marcoscaceres** [comment]
This is https://github.com/whatwg/html/issues/5129

**Comment by marcoscaceres** [comment]
@janiceshiu we should do this one together. The link above provides some guidance on what we need to do.
