### ISSUE TITLE
The frequency of the security popup

### ISSUE THREAD

**Issue by mr21** [w3c/pointerlock#58]
Hi :)

The PointerLock API appears to exists only for FPS games etc. but i have another scenario where this API is really useful but the security popups is starting to become annoying...

Locking the pointer for small and fine sliders is useful, with a small slider on screen we can ask the user to move the mouse more than the actual slider's width.
Also this API looks the only one to be able to lock the position AND provide solution to not being blocked by the edge of the screen.

May i invite you to visit gridsound.com/daw to have an example of this behavior, on this app i didn't implement the feature of moving the mouse in a really bigger area than the slider's size, but you still can feel the confort it could provide, you can already see the fact that there is no problem with sliders on the screen's edge)

Could we not show the same popup for the next 20sec or something like this? Because it's looks like this API has been though like the fullscreen API, there is no scenario where an app will fullscreen many times in the same 20sec, but locking a cursor yes

**Comment by scheib** [comment]
Thanks for writing.  The specification allows browsers to choose how to show exit instructions, and they may choose to show them each time.

I'm a Chrome developer, and we consider this a bug in Chrome https://crbug.com/989116.

**Comment by scheib** [comment]
(I suggest you star that issue https://crbug.com/989116 to increase the signal of interest in it being fixed, and to receive updates.)

**Comment by mr21** [comment]
done, thx :)
