### ISSUE TITLE
Clarify how requestPointerLock relies on user activation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/pointerlock#67]
Link to "activation triggering input event" is broken. Not sure what it should link to.

**Comment by mustaqahmed** [comment]
This should just point to the [definition](https://html.spec.whatwg.org/multipage/interaction.html#tracking-user-activation) in HTML spec.  That definition needs to be fixed but the PointerLock spec shouldn't worry about the details.

**Comment by marcoscaceres** [comment]
Right, so, I guess the question is, does it use transient or sticky activation? and will it consume the activation?

**Comment by mustaqahmed** [comment]
Yes, this needs to be clarified.  The "engagement gesture" idea essentially makes `requestPointerLock()` a [Transient activation-gated API](https://html.spec.whatwg.org/multipage/interaction.html#user-activation-gated-apis).  I will work on a PR next week.

**Comment by mustaqahmed** [comment]
This was fixed through https://github.com/w3c/pointerlock/pull/76.
